### ISSUE TITLE
newline inserted every 8192 characters of output

### ISSUE THREAD

**Issue by rich-murphey** [ducaale/ht#18]
A newline is inserted every 8192 characters of output.  It may land in the middle of a json value, causing the output to be invalid as json.

Regardless, this is super stuff.  Kudos!!!

**Comment by denysvitali** [comment]
OS?

If it's Windows, this might be relevant:
https://github.com/rust-lang/rust/blob/master/library/std/src/sys/windows/stdio.rs#L27

**Comment by rich-murphey** [comment]
OS was ubuntu. Thanks!

**Comment by rich-murphey** [comment]
I saw the newlines inserted after using 'cargo install ht --version 0.4.0' on ubuntu 20.04.

After installing from the master branch, the issue is not occuring.
So it looks like it's already been fixed.
