### ISSUE TITLE
Suggestion: Set Accept header

### ISSUE THREAD

**Issue by wezm** [ducaale/ht#6]
When supplying a JSON body to a request it might be a good idea to set the the HTTP `Accept` header (to `application/json`) so that well behaved web-servers will respond with errors in JSON instead of HTML.

Alternately there could be a method to manually set the `Accept` header like the `-H` option to `curl`.

**Comment by ducaale** [comment]
`ht`  does automatically set the `ACCEPT` header to `application/json, */*` whenever there is a request body. Although, now I realized that `ACCEPT` is being currently set twice.

```sh
$ ht --offline httpbin.org/post name=ali

POST /json HTTP/1.1
accept: */*
accept: application/json, */*
accept-encoding: gzip, deflate
connection: keep-alive
content-length: 14
content-type: application/json
host: httpbin.org

{
    "name": "ali"
}
```


>Alternately there could be a method to manually set the Accept header like the -H option to curl.

`ht` uses HTTPie's [request-item syntax](https://httpie.io/docs#request-items). This means you can use the colon separator to set headers.
```sh
ht --offline httpbin.org/json x-secret-key:12345

GET /json HTTP/1.1
accept: */*
accept-encoding: gzip, deflate
connection: keep-alive
host: httpbin.org
x-secret-key: 12345
```

Other undocumented request-item separators that `ht` now supports include:
*  `=`/`:=` for setting the request body's JSON fields.
* `==` for adding query strings.
* `@` for including files in multipart requests. 
* `:` for removing existing headers e.g `connection:`.
* `;` for including headers with empty values e.g `header-without-value;`.

**Comment by wezm** [comment]
> I realized that ACCEPT is being currently set twice (this is now fixed).

Ahh `*/*` coming first might have been the cause of my server responding with HTML instead of JSON. Thanks for the quick fix.

> ht uses HTTPie's request-item syntax. This means you can use the colon separator to set headers.

Cool, that seems quite convenient.

**Comment by wezm** [comment]
I built current master (b1c87fa86aba43ea082b253efe459cbe3836165c) and can confirm my issue is now fixed.
